import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, ArrowUpRight, Bell, Bot, CalendarDays, Check, ChevronRight, FileText, FolderOpen, LayoutDashboard, Loader2, Search, ShieldCheck, Sparkles, Upload, X } from 'lucide-react';
import './styles.css';

type Tender = { id:string; title:string; organization:string; location:string; deadline:string; value:string; category:string; match:number; status:string; tags:string[] };
const tenders:Tender[] = [
 {id:'TEN-2026-0184',title:'Annual GPU Maintenance & Overhaul Services',organization:'Airports Authority of India',location:'New Delhi',deadline:'28 Sep 2026',value:'₹4.8 Cr',category:'MRO',match:96,status:'Open',tags:['GPU','Maintenance','Aviation']},
 {id:'TEN-2026-0179',title:'Procurement of Ground Support Equipment',organization:'Air India Engineering Services',location:'Mumbai',deadline:'02 Oct 2026',value:'₹12.6 Cr',category:'Equipment',match:92,status:'Open',tags:['GSE','Aircraft','Equipment']},
 {id:'TEN-2026-0166',title:'Aircraft Component Repair and Maintenance',organization:'Hindustan Aeronautics Limited',location:'Bengaluru',deadline:'05 Oct 2026',value:'₹8.2 Cr',category:'MRO',match:88,status:'Open',tags:['Aircraft','MRO','Repair']},
 {id:'TEN-2026-0148',title:'Supply and Maintenance of Airfield Lighting',organization:'Delhi International Airport',location:'New Delhi',deadline:'19 Sep 2026',value:'₹3.1 Cr',category:'Infrastructure',match:71,status:'Closing soon',tags:['Airfield','Maintenance']}
];
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';

function App(){
 const [query,setQuery]=useState('GPU maintenance'); const [active,setActive]=useState<Tender>(tenders[0]); const [tab,setTab]=useState('Overview'); const [uploading,setUploading]=useState(false); const [analysis,setAnalysis]=useState<any>(null); const input=useRef<HTMLInputElement>(null);
 const found=useMemo(()=>tenders.filter(t=>!query||`${t.title} ${t.organization} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase().split(' ')[0])),[query]);
 async function upload(file?:File){if(!file)return; setUploading(true); const fd=new FormData();fd.append('file',file);try{const r=await fetch(`${API}/documents/analyze`,{method:'POST',body:fd});if(!r.ok)throw Error();setAnalysis(await r.json())}catch{setAnalysis({title:file.name.replace('.pdf',''),organization:'Tender issuer',deadline:'Review source',estimated_value:'Not disclosed',summary:'The backend is not running, so this is a local preview. Start the FastAPI service to extract data from your PDF.',eligibility:['Business registration','Relevant experience'],required_documents:['Technical proposal','Financial bid'],risks:['Review dates and eligibility in source document.']})}finally{setUploading(false)}}
 return <div className="app"><aside><div className="brand"><span className="logo"><Sparkles size={18}/></span><span>Tender<span>IQ</span></span></div><nav><a className="selected"><LayoutDashboard/>Dashboard</a><a><Search/>Tender discovery</a><a><FileText/>My tenders <b>3</b></a><a><FolderOpen/>Document vault</a></nav><div className="navlabel">WORKSPACE</div><nav><a><ShieldCheck/>Bid readiness</a><a><Bot/>AI copilot</a></nav><div className="profile"><div className="avatar">MK</div><div><strong>Mohit Khatana</strong><small>Enterprise plan</small></div><ChevronRight size={16}/></div></aside>
 <main><header><div className="crumb">Tenders <ChevronRight size={14}/> <strong>Discovery</strong></div><div className="header-actions"><button className="icon"><Bell size={18}/><i/></button><button className="upload" onClick={()=>input.current?.click()}><Upload size={17}/> Upload tender</button><input ref={input} type="file" accept="application/pdf" hidden onChange={e=>upload(e.target.files?.[0])}/></div></header>
 <section className="hero"><div className="eyebrow"><Sparkles size={15}/> AI-POWERED PROCUREMENT INTELLIGENCE</div><h1>Find the next tender<br/><em>worth winning.</em></h1><p>Search opportunities, understand tender documents, and prepare stronger bids — all in one intelligent workspace.</p><div className="searchbox"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tenders, e.g. GPU maintenance"/><kbd>⌘ K</kbd></div><div className="suggestions"><span>Popular:</span>{['GPU maintenance','Ground support equipment','Aircraft maintenance'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div></section>
 <section className="content"><div className="results"><div className="section-top"><div><h2>Matching opportunities <span>{found.length}</span></h2><p>AI-ranked based on your organization profile</p></div><button className="filter">All categories <ChevronRight size={15}/></button></div><div className="cards">{found.map(t=><article className={'card '+(active.id===t.id?'active':'')} key={t.id} onClick={()=>setActive(t)}><div className="match">{t.match}%<small>match</small></div><div className="card-body"><div className="card-meta"><span>{t.category}</span><i>•</i>{t.id}</div><h3>{t.title}</h3><p>{t.organization} <i>·</i> {t.location}</p><div className="tags">{t.tags.map(x=><label key={x}>{x}</label>)}</div></div><div className="deadline"><span className={t.status==='Closing soon'?'urgent':''}>{t.status}</span><p><CalendarDays size={14}/>{t.deadline}</p><strong>{t.value}</strong></div></article>)}</div></div>
 <aside className="insight"><div className="panel-title"><div><span>AI TENDER BRIEF</span><h2>{analysis?'Document analysis':'Opportunity intelligence'}</h2></div><Sparkles className="purple" size={20}/></div>{analysis?<Analysis data={analysis}/>:<Opportunity tender={active} tab={tab} setTab={setTab}/>}<button className="open">Open full workspace <ArrowUpRight size={16}/></button></aside></section></main></div>}
function Opportunity({tender,tab,setTab}:{tender:Tender;tab:string;setTab:(x:string)=>void}){return <><div className="brief-head"><div className="brief-icon"><FileText size={21}/></div><div><h3>{tender.title}</h3><p>{tender.organization}</p></div></div><div className="tabs">{['Overview','Requirements','Risks'].map(x=><button onClick={()=>setTab(x)} className={tab===x?'on':''} key={x}>{x}</button>)}</div>{tab==='Overview'?<><p className="summary">A high-fit opportunity aligned with your aviation maintenance and ground-support capabilities. Strong prior experience will be essential.</p><Metric label="Tender value" value={tender.value}/><Metric label="Submission deadline" value={tender.deadline}/><div className="signal"><Sparkles size={16}/><div><strong>Why this is a strong fit</strong><p>Matches 4 capabilities in your company profile.</p></div></div></>:<Checklist risk={tab==='Risks'}/>}</>}
function Analysis({data}:{data:any}){return <><div className="brief-head"><div className="brief-icon"><FileText size={21}/></div><div><h3>{data.title}</h3><p>{data.organization}</p></div></div><div className="extract-note"><Check size={14}/> {data.source||'AI extraction complete'}</div><p className="summary">{data.summary}</p><Metric label="Estimated value" value={data.estimated_value}/><Metric label="Deadline" value={data.deadline}/><Checklist items={data.required_documents} /><div className="risk"><AlertTriangle size={16}/><p>{data.risks?.[0]}</p></div></>}
function Metric({label,value}:{label:string,value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}; function Checklist({items,risk}:{items?:string[],risk?:boolean}){const x=items||['5+ years of relevant experience','ISO 9001:2015 certification','Minimum annual turnover requirement'];return <div className={risk?'risk-list':'checklist'}><h4>{risk?'Potential risks':'Required documents'}</h4>{x.map((a,i)=><p key={i}>{risk?<AlertTriangle size={15}/>:<Check size={15}/>} {a}</p>)}</div>}; createRoot(document.getElementById('root')!).render(<App/>);
